resources:
  repositories:
  - repository: templates
    type: github
    name: pingdong/azure.devops.templates
    ref: refs/heads/master
    endpoint: GitHub  
  - repository: infrastructure
    type: github
    name: pingdong/newmoon.infrastructure
    ref: refs/heads/master
    endpoint: GitHub

variables:
- name  : local#project.name
  value : Venues.FunctionApp
- name  : local#service.name
  value : newmoon
- name  : local#environment.dev
  value : dev
- name  : local#environment.integrationTestings
  value : integration.testings
- name  : local#environment.prod
  value : prod
# Existing issue:
# A few value in deployment task, such as Pool:vmImage, environment, azureSubscription, 
#   are only read from stage-level variables or variable groups
#   https://github.com/microsoft/azure-pipelines-extensions/issues/832
# The ultimate reason:
#   Azure DevOps need to check all permissions 
#   at the beginning of the run of the pipeline
- group : Pipeline

trigger:
  batch: false  # batch changes if true; 
                #   start a new build for every push if false (default)

pr:
  autoCancel: true   # Indicates whether additional pushes to a PR 
                     #   should cancel in-progress runs for the same PR.
                     # Defaults to true

schedules:
- cron: '0 1 * * *' # Every day at 1 A.M.
  displayName: Nightly Build
  branches:
    include:
    - master
  always: true      # Whether to always run the pipeline or only if 
                    #   there have been source code changes 
                    #   since the last successful scheduled run. 
                    # The default is false.

stages:
# Quality Control
- stage: QualityControl
  displayName: Quality Control
  variables:
    - group: Build
    - group: Test.Static
    - group: Test.Unit
    - group: Test.Integration
  jobs:
  # Static Testing
  - template: templates\test.static.yml@templates
    parameters:
      vmImage: $(pipeline#vmImage)

  # Unit Testing
  - template: templates\test.unit.yml@templates
    parameters:
      vmImage: $(pipeline#vmImage)
      buildConfiguration: $(build#configuration.release)
      projectName: ${{ variables['local#project.name'] }}   # Can't use $(local@app.name) here
                                                    #  as parameter appName is used to build variable in compile time inside template.
      coverageHistoryFeed: $(test.unit#coverage.history.feed)
      sonarcloudOrganization: $(test.unit#sonarcloud.organization)
     
  # Validating Infrastructure
  - job: TerraformValidating
    displayName: Validating Terraform
    pool:
      vmImage: $(pipeline#vmImage)
    workspace:
      clean: all
    steps:
    - checkout: infrastructure

    - template: templates\terraform.validate.yml@templates
      parameters:
        workingDirectory: $(Build.SourcesDirectory)/terraform

  # Integration Testing
  - job: IntegrationTesting
    displayName: Integration Testing
    pool:
      vmImage: $(pipeline#vmImage)
    variables:
    - group: Pipeline.Terraform
    - group: Pipeline.Terraform.Secret
    - name : local#integration.testing.parameter.target
      value: '{ features = ["venue"]   suffix = "298F" }'  # TODO: Generate random suffix
    workspace:
      clean: all
    condition: |
      or
      (
        eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        eq(variables['Build.Reason'], 'PullRequest'),
        eq(variables['Build.Reason'], 'Schedule')
      )
    steps:
    - checkout: infrastructure

    # Deploying Shared Resources of Integration Testing 
    - template: templates\terraform.apply.yml@templates
      parameters:
        azureSubscription: $(pipeline#azure.subscription)
        stateResourceGroup: $(pipeline.terraform#resourceGroup)
        stateStorageAccount: $(pipeline.terraform#storageAccount)
        stateStorageAccountContainer: $(pipeline.terraform#storageAccount.container.integrationTestings)
        stateStorageAccountKey: $(StateStorageKey) # <- from Pipeline.Terraform.Secret
        workingDirectory: $(Build.SourcesDirectory)/terraform
        variables: '-var service=$(local#service.name) -var environment=$(local#environment.integrationTestings) -var location=$(pipeline#azure.location) -var target=integration_test-shared'
    
    # Building Resourse
    - template: templates\build.yml@templates
      parameters:
        vmImage: $(pipeline#vmImage)
        projectName: $(local#project.name)
        buildConfiguration: $(build#configuration.release)
    
    # Deploying Testing Resources
    - template: templates\terraform.apply.yml@templates
      parameters:
        workingDirectory: $(Build.SourcesDirectory)/terraform
        variables: '-var service=$(local#service.name) -var environment=$(local#environment.integrationTestings) -var location=$(pipeline#azure.location) -var target=integration_test -var integration_testing=$(local#integration.testing.parameter.target)'
    
    # Running Integration Testings
    - task: DotNetCoreCLI@2
      displayName: Running Integration Testings
      inputs:
        command: test
        arguments: '--no-build --configuration ${{ parameters.buildConfiguration }}'
        publishTestResults: true
        projects: '**/*.[Ii]ntegration[Tt]ests/*.csproj'

    # Tearing down Integration Testings Resources
    - template: templates\terraform.destory.yml@templates
      parameters:
        workingDirectory: $(Build.SourcesDirectory)/terraform
        variables: '-var service=$(local#service.name) -var environment=$(local#environment.integrationTestings) -var location=$(pipeline#azure.location) -var target=integration_test -var integration_testing=$(local#integration.testing.parameter.target)'
    
# Build
- stage: Build
  displayName: Building
  dependsOn: QualityControl
  condition: |
    and
    (
      succeeded(),
      eq(variables['Build.SourceBranch'], 'refs/heads/master'),
      ne(variables['Build.Reason'], 'Schedule')
    )
  variables:
  - group: Build
  jobs:
  - template: templates\build.yml@templates
    parameters:
      vmImage: $(pipeline#vmImage)
      projectName: $(local#project.name)
      buildConfiguration: $(build#configuration.release)
  
# Deployment
#   DEV
- stage: VerifyDev
  displayName: 'Verify: DEV'
  dependsOn: Build
  variables:
  - group: Pipeline.Terraform
  - group: Pipeline.Terraform.Secret
  jobs:
  - job: TerraformPlanning
    displayName: Verifying Infrastructure
    pool:
      vmImage: $(pipeline#vmImage)
    workspace:
      clean: all
    steps:
    - checkout: infrastructure
  
    - template: templates\terraform.plan.yml@templates
      parameters:
        azureSubscription: $(pipeline#azure.subscription)
        stateResourceGroup: $(pipeline.terraform#resourceGroup)
        stateStorageAccount: $(pipeline.terraform#storageAccount)
        stateStorageAccountContainer: $(pipeline.terraform#storageAccount.container.dev)
        stateStorageAccountKey: $(StateStorageKey)  # <- from Pipeline.Terraform.Secret
        workingDirectory: $(Build.SourcesDirectory)/terraform
        variables: '-var service=$(local#service.name) -var environment=$(local#environment.dev) -var location=$(pipeline#azure.location)'

- stage: DeployToDev
  displayName: 'Deploying: DEV'
  dependsOn: VerifyDev
  variables:
  - group: Pipeline.Terraform
  - group: Pipeline.Terraform.Secret
  jobs:
  - deployment: Deploying
    displayName: Deploying
    environment: $(pipeline#environment.deploy.dev)
    pool:
      vmImage: $(pipeline#vmImage)
    strategy:
      runOnce:
        deploy:
          steps:
          # Deploy Infrastructure Change
          - checkout: infrastructure

          - template: templates\terraform.apply.yml@templates
            parameters:
              azureSubscription: $(pipeline#azure.subscription)
              stateResourceGroup: $(pipeline.terraform#resourceGroup)
              stateStorageAccount: $(pipeline.terraform#storageAccount)
              stateStorageAccountContainer: $(pipeline.terraform#storageAccount.container.dev)
              stateStorageAccountKey: $(StateStorageKey) # <- from Pipeline.Terraform.Secret
              workingDirectory: $(Build.SourcesDirectory)/terraform
              variables: '-var service=$(local#service.name) -var environment=$(local#environment.dev) -var location=$(pipeline#azure.location)'
              
          # Deploy Func
          - template: templates\deploy.functionapp.yml@templates
            parameters:
              azureSubscription: $(pipeline#azure.subscription)
              funcName: $(TF_OUT_FUNC-VENUE-NAME)

#   PROD
- stage: VerifyProd
  displayName: 'Verifying: PROD'
  dependsOn: DeployToDev
  variables:
  - group: Pipeline.Terraform
  - group: Pipeline.Terraform.Secret
  jobs:
  - job: TerraformPlanning
    displayName: Verifying Infrastructure
    pool:
      vmImage: $(pipeline#vmImage)
    workspace:
      clean: all
    steps:
    - checkout: infrastructure
  
    - template: templates\terraform.plan.yml@templates
      parameters:
        azureSubscription: $(pipeline#azure.subscription)
        stateResourceGroup: $(pipeline.terraform#resourceGroup)
        stateStorageAccount: $(pipeline.terraform#storageAccount)
        stateStorageAccountContainer: $(pipeline.terraform#storageAccount.container.prod)
        stateStorageAccountKey: $(StateStorageKey)  # <- from Pipeline.Terraform.Secret
        workingDirectory: $(Build.SourcesDirectory)/terraform
        variables: '-var service=$(local#service.name) -var environment=$(local#environment.prod) -var location=$(pipeline#azure.location)'

- stage: DeployToProd
  displayName: 'Deploying: PROD'
  dependsOn: VerifyProd
  variables:
  - group: Pipeline.Terraform
  - group: Pipeline.Terraform.Secret
  jobs:
  - deployment: Deploying
    displayName: Deploying
    environment: $(pipeline#environment.deploy.prod)
    pool:
      vmImage: $(pipeline#vmImage)
    strategy:
      runOnce:
        deploy:
          steps:
          # Deploy Infrastructure Change
          - checkout: infrastructure

          - template: templates\terraform.apply.yml@templates
            parameters:
              azureSubscription: $(pipeline#azure.subscription)
              stateResourceGroup: $(pipeline.terraform#resourceGroup)
              stateStorageAccount: $(pipeline.terraform#storageAccount)
              stateStorageAccountContainer: $(pipeline.terraform#storageAccount.container.prod)
              stateStorageAccountKey: $(StateStorageKey) # <- from Pipeline.Terraform.Secret
              workingDirectory: $(Build.SourcesDirectory)/terraform
              variables: '-var service=$(local#service.name) -var environment=$(local#environment.prod) -var location=$(pipeline#azure.location)'
              
          # Deploy Func
          - template: templates\deploy.functionapp.yml@templates
            parameters:
              azureSubscription: $(pipeline#azure.subscription)
              funcName: $(TF_OUT_FUNC-VENUE-NAME)
              # Slot
              enableSlot: true
              resourceGroupName: $(TF_OUT_RG-COMPUTE_NAME)
              slotName: $(TF_OUT_FUNC-VENUE-SLOT_NAME)
      