resources:
  repositories:
  - repository: templates
    type: github
    name: pingdong/azure.devops.templates
    ref: refs/heads/master
    endpoint: GitHub

variables:
- group : Pipeline   # deployment Task requires the variable of Pool:vmImage on the pipeline level
- name  : local#app.name
  value : Venues.FunctionApp

trigger:
  batch: true

pr:
  autoCancel: true   # Cancel previous build if check in multiple times

schedules:
- cron: '0 1 * * *' # Every day at 1 A.M.
  displayName: Nightly Build
  branches:
    include:
    - master
  always: true      # Even no code change

stages:
# # Quality Control
# - stage: QualityControl
#   displayName: Quality Control
#   jobs:
#   - template: templates\test_static.yml@templates

#   - template: templates\test_unit.yml@templates
#     parameters:
#       appName: ${{ variables['local#app.name'] }}  # Can't use $(local@app.name) here
     
#   - template: templates\test_integration.yml@templates

# Build
- stage: Build
  displayName: Building
  # dependsOn: QualityControl
  condition: |
    and
    (
      succeeded(),
      eq(variables['Build.SourceBranch'], 'refs/heads/master'),
      ne(variables['Build.Reason'], 'Schedule')
    )
  jobs:
  - template: templates\build.yml@templates
    parameters:
      appName: ${{ variables['local#app.name'] }}
  
# Deployment
- stage: DeployToDev
  displayName: 'Deploying: DEV'
  dependsOn: Build
  variables:
  - group: Dev.Deploy
  # Existing error to read the variables from library
  - name: local#environment
    value: dev_deploy
  - name: local#azure.subscription
    value: Azure
  jobs:
  - template: templates\deploy_functionapp.yml@templates
    parameters:
      vmImage: $(pipeline#vmImage)
      environment: $(local#environment) 
      funcName: $(deploy#venue.app)
      azureSubscription: $(local#azure.subscription)
 
- stage: DeployToProd
  displayName: 'Deploying: PROD'
  dependsOn: DeployToDev
  variables:
  - group: Prod.Deploy
  # Existing error to read the variables from library
  - name: local#environment
    value: prod_deploy
  - name: local#azure.subscription
    value: Azure
  jobs:
  - template: templates\deploy_functionapp.yml@templates
    parameters:
      vmImage: $(pipeline#vmImage)
      environment: $(local#environment)
      funcName: $(deploy#venue.app)
      azureSubscription: $(local#azure.subscription)
      enableSlot: true
      resourceGroupName: $(deploy#venue.resourcegroup)
      slotName: $(deploy#venue.app.slot)
      