resources:
  repositories:
  - repository: templates
    type: github
    name: pingdong/azure.devops.templates
    ref: refs/heads/master
    endpoint: GitHub

variables:
- name  : local#app.name
  value : Venues.FunctionApp
# Existing issue:
# A few value in deployment task, such as Pool:vmImage, environment, azureSubscription, 
#   are only read from stage-level variables or variable groups
#   https://github.com/microsoft/azure-pipelines-extensions/issues/832
# The ultimate reason:
#   Azure DevOps need to check all permissions 
#   at the beginning of the run of the pipeline
- group : Deploy

trigger:
  batch: false  # batch changes if true; 
                #   start a new build for every push if false (default)

pr:
  autoCancel: true   # Indicates whether additional pushes to a PR 
                     #   should cancel in-progress runs for the same PR.
                     # Defaults to true

schedules:
- cron: '0 1 * * *' # Every day at 1 A.M.
  displayName: Nightly Build
  branches:
    include:
    - master
  always: true      # Whether to always run the pipeline or only if 
                    #   there have been source code changes 
                    #   since the last successful scheduled run. 
                    # The default is false.

stages:
# Quality Control
- stage: QualityControl
  displayName: Quality Control
  jobs:
  # Static Testing
  - template: templates\test_static.yml@templates

  # Unit Testing
  - template: templates\test_unit.yml@templates
    parameters:
      appName: ${{ variables['local#app.name'] }}  # Can't use $(local@app.name) here
     
  # Integration Testing
  - template: templates\test_integration.yml@templates

# Build
- stage: Build
  displayName: Building
  dependsOn: QualityControl
  condition: |
    and
    (
      succeeded(),
      eq(variables['Build.SourceBranch'], 'refs/heads/master'),
      ne(variables['Build.Reason'], 'Schedule')
    )
  jobs:
  - template: templates\build.yml@templates
    parameters:
      appName: $(local#app.name)
  
# Deployment
- stage: DeployToDev
  displayName: 'Deploying: DEV'
  dependsOn: Build
  variables:
  - group: Dev.Deploy
  jobs:
  - template: templates\deploy_functionapp.yml@templates
    parameters:
      vmImage: $(deploy#vmImage)
      environment: $(deploy#dev.environment)
      azureSubscription: $(deploy#dev.azure.subscription)
      funcName: $(deploy#venue.app)
 
- stage: DeployToProd
  displayName: 'Deploying: PROD'
  dependsOn: DeployToDev
  variables:
  - group: Prod.Deploy
  jobs:
  - template: templates\deploy_functionapp.yml@templates
    parameters:
      vmImage: $(deploy#vmImage)
      environment: $(deploy#prod.environment)
      azureSubscription: $(deploy#prod.azure.subscription)
      funcName: $(deploy#venue.app)
      enableSlot: true
      resourceGroupName: $(deploy#venue.resourcegroup)
      slotName: $(deploy#venue.app.slot)
      