# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - develop
  - master

pool:
  vmImage: 'ubuntu-latest'

workspace:
    clean: all

variables:
  buildConfiguration: 'Debug'
  BuildConfiguration.Release: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: restore
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: pekspro.pekspro-efcore-migration-script-generator.efcore-migration-script-generator.efcore-migration-script-generator-task@0
  displayName: 'Generate Migration Scripts'
  inputs:
    projectpath: src/infrastructure/Places.Infrastructure.csproj
    databasecontexts: DefaultDbContext
    targetfolder: '$(Build.ArtifactStagingDirectory)'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  env:
    ConnectionStrings__Default: $(Place-Db-ConnectionString)

- task: DotNetCoreCLI@2
  displayName: 'Release Build'
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration.Release) --output $(Build.ArtifactStagingDirectory)'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration.Release) --output $(Build.ArtifactStagingDirectory)'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
