resources:
  repositories:
  - repository: templates
    type: github
    name: pingdong/azure.devops.templates
    ref: refs/heads/master
    endpoint: GitHub

variables:
- name: local#app.name
  value: Venues.FunctionApp

trigger:
  batch: true

pr:
  autoCancel: true   # Cancel previous build if check in multiple times

schedules:
- cron: '0 1 * * *' # Every day at 1 A.M.
  displayName: Nightly Build
  branches:
    include:
    - master
  always: true      # Even no code change

stages:
# Quality Control
- stage: QualityControl
  displayName: Quality Control
  jobs:
  - template: templates\static_test.yml

  - template: templates\unit_test.yml
    parameters:
      appName: ${{ variables['local#app.name'] }}
     
  - template: templates\integration_test.yml

# Build
- stage: Build
  displayName: Building
  dependsOn: QualityControl
  condition: |
    and
    (
      succeeded(),
      eq(variables['Build.SourceBranch'], 'refs/heads/master'),
      ne(variables['Build.Reason'], 'Schedule')
    )
  jobs:
  - template: templates\build.yml
    parameters:
      appName: $(local#app.name)
  
# Deployment
- stage: DeployToDev
  displayName: 'Deploying: DEV'
  dependsOn: Build
  variables:
  - group: Deploy.Dev
  jobs:
  - template: templates\deploy_functionapp.yml
    parameters:
      environment: dev_deploy
      funcName: $(deploy#venue.app)

- stage: DeployToProd
  displayName: 'Deploying: PROD'
  dependsOn: DeployToDev
  variables:
  - group: Deploy.Prod
  jobs:
  - template: templates\deploy_functionapp.yml
    parameters:
      environment: dev_prod
      funcName: $(deploy#venue.app)
      enableSlot: true
      resourceGroupName: $(deploy#venue.resourcegroup)
      slotName: $(deploy#venue.app.slot)
      

