resources:
  repositories:
  - repository: templates
    type: github
    name: pingdong/azure.devops.templates
    ref: refs/heads/master
    endpoint: GitHub  
  - repository: infrastructure
    type: github
    name: pingdong/newmoon.infrastructure
    ref: refs/heads/master
    endpoint: GitHub

variables:
- name  : local#app.name
  value : Venues.FunctionApp
- name  : local#service.name
  value : Newmoon
- name  : local#environment.dev
  value : dev
- name  : local#environment.prod
  value : prod
# Existing issue:
# A few value in deployment task, such as Pool:vmImage, environment, azureSubscription, 
#   are only read from stage-level variables or variable groups
#   https://github.com/microsoft/azure-pipelines-extensions/issues/832
# The ultimate reason:
#   Azure DevOps need to check all permissions 
#   at the beginning of the run of the pipeline
- group : Pipeline

trigger:
  batch: false  # batch changes if true; 
                #   start a new build for every push if false (default)

pr:
  autoCancel: true   # Indicates whether additional pushes to a PR 
                     #   should cancel in-progress runs for the same PR.
                     # Defaults to true

schedules:
- cron: '0 1 * * *' # Every day at 1 A.M.
  displayName: Nightly Build
  branches:
    include:
    - master
  always: true      # Whether to always run the pipeline or only if 
                    #   there have been source code changes 
                    #   since the last successful scheduled run. 
                    # The default is false.

stages:
# Quality Control
- stage: QualityControl
  displayName: Quality Control
  variables:
    - group: Build
    - group: Test.Static
    - group: Test.Unit
    - group: Test.Integration
  jobs:
  # Static Testing
  - template: templates\test.static.yml@templates
    parameters:
      vmImage: ${{ variables['pipeline#vmImage'] }}

  # Unit Testing
  - template: templates\test.unit.yml@templates
    parameters:
      vmImage: $(pipeline#vmImage)
      buildConfiguration: $(build#configuration.release)
      appName: $(local#app.name) # ${{ variables['local#app.name'] }}   # Can't use $(local@app.name) here
                                                    #  as parameter appName is used to build variable in compile time inside template.
      coverageHistoryFeed: $(test.unit#coverage.history.feed)
      sonarcloudOrganization: $(test.unit#sonarcloud.organization)
     
  # Integration Testing
  - template: templates\test.integration.yml@templates
    parameters:
      vmImage: $(pipeline#vmImage)

  # Validating Infrastructure
  - template: templates\terraform.validate.yml@templates
    parameters:
      vmImage: $(pipeline#vmImage)
      workingDirectory: infrastructure\terraform@infrastructure

# Build
- stage: Build
  displayName: Building
  dependsOn: QualityControl
  condition: |
    and
    (
      succeeded(),
      eq(variables['Build.SourceBranch'], 'refs/heads/master'),
      ne(variables['Build.Reason'], 'Schedule')
    )
  variables:
  - group: Build
  jobs:
  - template: templates\build.yml@templates
    parameters:
      vmImage: $(pipeline#vmImage)
      appName: $(local#app.name)
      buildConfiguration: $(build#configuration.release)
  
# Deployment
#   DEV
- stage: PrepareDev
  displayName: 'Preparing: DEV'
  dependsOn: Build
  variables:
  - group: Infrastructure
  - group: Pipeline.Terraform
  - group: Pipeline.Terraform.Secret
  jobs:
  - template: templates\terraform.plan.yml@templates
    parameters:
      vmImage: $(pipeline#vmImage)
      azureSubscription: $(pipeline#azure.subscription)
      stateResourceGroup: $(pipeline.terraform#resourceGroup)
      stateStorageAccount: $(pipeline.terraform#storageAccount)
      stateStorageAccountContainer: $(pipeline.terraform#storageAccount.container.dev)
      stateStorageAccountKey: $(StateStorageKey)  # <- from Pipeline.Terraform.Secret
      workingDirectory: infrastructure\terraform@infrastructure
      arguments: |
        -var service=$(local#service.name) \
        -var environment=$(local#environment.dev) \
        -var location=$(infrastructure#location)

- stage: DeployToDev
  displayName: 'Deploying: DEV'
  dependsOn: PrepareDev
  variables:
  - group: Pipeline.Terraform
  - group: Pipeline.Terraform.Secret
  jobs:
  - deployment: Deploying
    displayName: Deploying
    environment: $(pipeline#environment.deploy.dev)
    pool:
      vmImage: $(pipeline#vmImage)
    strategy:
      runOnce:
        deploy:
          steps:
          # Deploy Infrastructure Change
          - template: templates\terraform.apply.yml@templates
            parameters:
              azureSubscription: ${{ variables['pipeline#azure.subscription'] }}
              stateResourceGroup: $(pipeline.terraform#resourceGroup)
              stateStorageAccount: $(pipeline.terraform#storageAccount)
              stateStorageAccountContainer: $(pipeline.terraform#storageAccount.container.dev)
              stateStorageAccountKey: $(StateStorageKey) # <- from Pipeline.Terraform.Secret
              workingDirectory: infrastructure\terraform@infrastructure
              
          # Deploy Func
          - template: templates\deploy.functionapp.yml@templates
            parameters:
              azureSubscription: ${{ variables['pipeline#azure.subscription.dev'] }}
              funcName: newmoon-dev-func-venues  # TODO: Should come from terraform output

  # TODO: PROD environment


  # - template: templates\deploy.functionapp.yml@templates
  #   parameters:
  #     vmImage: $(pipeline#vmImage)
  #     environment: $(pipeline#environment.deploy.prod)
  #     azureSubscription: $(pipeline#azure.subscription.prod)
  #     funcName: func-newmoon-prod   # TODO: Should come from terraform output
  #     # Slot
  #     enableSlot: true
  #     resourceGroupName: rg-newmoon-prod    # TODO: Should come from terraform output
  #     slotName: stage     # TODO: Should come from terraform output
      